### ISSUE TITLE
how to get embedding

### ISSUE THREAD

**Issue by wawpaopao** [samgoldman97/enz-pred#1]
May I ask how to get molecular embeddings from pretrained vae? 
thank you very much

**Comment by samgoldman97** [comment]
If you're interested in extracting embeddings from the JT-VAE in Jin et al., you can use this fork of their repository: https://github.com/samgoldman97/icml18-jtnn.

You can generate embeddings as described in the README and then load those embeddings directly. I'll also note that we find circular Morgan fingerprints to be better featurization than those from the JT-VAE latent space.
