### ISSUE TITLE
There is no 'data/program_cache/' in this depot

### ISSUE THREAD

**Issue by NaiveLittleTiger** [samgoldman97/enz-pred#4]
When I try to run this commond "python run_scripts/run_combinations_slurm.py configs/2021_06_30_example_launch.json" 
Then I get the following error 'data/program_cache/4cc6e1bd0f2fa6f1913a78a30452e26b'.
It seems like there is no directory named program_cache in your depot, has anyone met the same program? Thank you very much

**Comment by samgoldman97** [comment]
Thanks for pointing this out! I just added a .gitkeep file to make sure the `data/program_cache directory` exists , which should correct this. Let me know if this issue persists.
