### ISSUE TITLE
the hyperparameter optimized on halogenase dataset did not find

### ISSUE THREAD

**Issue by NaiveLittleTiger** [samgoldman97/enz-pred#5]
Hello, anyone can help me? I meet this error when I try to run qsar_multi_json
results/dense/2021_05_25_qsar_olea_hyperopt_seed_1/halogenase_NaBr_binary/linear/22e7a0cd6f69ac7006eefd353b2be9f9/2021_05_28-095931_optuna_params.json not find
maybe please upload the optuna_params.json file , thank you very much

**Comment by samgoldman97** [comment]
I have uploaded the hyperparam files and marking as closed.
