### ISSUE TITLE
ModuleNotFoundError: No module named 'bepler_embedding'

### ISSUE THREAD

**Issue by sonderca** [samgoldman97/enz-pred#6]
Sorry, when I try to use this project, the installation process always says No module named 'bepler_embedding', and I can't find the module on the Internet, please ask if the module has been iterated or replaced by another method

**Comment by samgoldman97** [comment]
Please make sure you are downloading the pip installed entries in the environment.yml as well. bepler_embeddings are included there (git+https://github.com/samgoldman97/protein-sequence-embedding-iclr2019)

**Comment by sonderca** [comment]
I still can't install tape-proteins==0.4 after trying to install multiple torchs Is it related to the version of python?
![image](https://user-images.githubusercontent.com/103834881/225836417-bf731348-2531-4057-ab6d-09a54b450c2d.png)
